# Generated by Django 2.1.1 on 2020-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doktermodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('kode_rs', models.CharField(max_length=50)),
                ('id_dokter', models.CharField(max_length=60)),
            ],
        ),
    ]
