# Generated by Django 2.1.1 on 2020-05-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiturwulan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doktermodels',
        ),
    ]
