# Generated by Django 2.2.5 on 2020-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiturhilmi', '0003_auto_20200505_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTindakanPoliklinik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDPoliklinik', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('NamaTindakan', models.TextField(max_length=50)),
                ('Deskripsi', models.TextField(max_length=100)),
                ('Tarif', models.TextField(max_length=50)),
            ],
        ),
    ]
