# Generated by Django 2.2.5 on 2020-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiturhilmi', '0004_modeltindakanpoliklinik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltindakan',
            name='IDTindakanKlinik',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modeltindakan',
            name='IDTransaksi',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modeltindakanpoliklinik',
            name='Deskripsi',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modeltindakanpoliklinik',
            name='NamaTindakan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='modeltindakanpoliklinik',
            name='Tarif',
            field=models.CharField(max_length=20),
        ),
    ]
