# Generated by Django 2.2.5 on 2020-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiturhilmi', '0006_auto_20200506_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltindakan',
            name='IDTransaksi',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=50),
        ),
    ]
